version: '3.8'

services:

  nginx:
    build: ./nginx-html
    volumes:
      - ./nginx-html:/usr/share/nginx/html
      - static_volume:/home/app/web/project/static
    ports:
      - 8080:80
    depends_on:
      - web

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/doko_flask/static
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod:
  static_volume:
